Repository opendatahub-io/kubeflow, pull requests merged in 2024-04, with the labels that each got.

#303 fix: remove replace from go.mod file
  components/common/reconcilehelper/util.go
  components/notebook-controller/controllers/notebook_controller.go
  components/notebook-controller/go.mod
Labels: approved, lgtm

#304 create configmap and mount for the first workbench in NS
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: lgtm

#308 fix: remove handler for notebook update event
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm

#309 fix: add nil checks to prevent unit tests from failing
  components/notebook-controller/controllers/notebook_controller.go
Labels: approved, lgtm

#302 Bring back GitHub Actions testing
  .github/issue_label_bot.yaml
  .github/pull.yml
  .github/stale.yml
  .github/workflows/auto-add-issue-to-project.yaml
  .github/workflows/centraldb_angular_backend_test.yaml
  .github/workflows/centraldb_angular_docker_publish.yaml
  .github/workflows/centraldb_angular_frontend_test.yaml
  .github/workflows/centraldb_angular_intergration_test.yaml
  .github/workflows/centraldb_docker_publish.yaml
  .github/workflows/centraldb_frontend_tests.yaml
  .github/workflows/centraldb_intergration_test.yaml
  .github/workflows/common_frontend_tests.yaml
  .github/workflows/jwa_backend_unittests.yaml
  .github/workflows/jwa_docker_publish.yaml
  .github/workflows/jwa_frontend_tests.yaml
  .github/workflows/jwa_intergration_test.yaml
  .github/workflows/kfam_docker_publish.yaml
  .github/workflows/nb_controller_docker_publish.yaml
  .github/workflows/nb_controller_intergration_test.yaml
  .github/workflows/nb_server_codeserver_python_docker_publish.yaml
  .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
  .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
  .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
  .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
  .github/workflows/notebook_controller_unit_test.yaml
  .github/workflows/poddefaults_docker_publish.yaml
  .github/workflows/poddefaults_intergration_test.yaml
  .github/workflows/prof_controller_docker_publish.yaml
  .github/workflows/prof_controller_unit_test.yaml
  .github/workflows/profiles_kfam_intergration_test.yaml
  .github/workflows/tb_controller_docker_publish.yaml
  .github/workflows/tb_controller_intergration_test.yaml
  .github/workflows/triage_issues.yaml
  .github/workflows/twa_docker_publish.yaml
  .github/workflows/twa_frontend_tests.yaml
  .github/workflows/twa_intergration_test.yaml
  .github/workflows/vwa_docker_publish.yaml
  .github/workflows/vwa_frontend_tests.yaml
  .github/workflows/vwa_intergration_test.yaml
Labels: approved, lgtm, ok-to-test

#316 chore: add Dependabot configuration file
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test
