Repository opendatahub-io/kubeflow, pull requests merged in 2024-11, with the labels that each got.

#439 RHOAIENG-14552: Reapply "RHOAIENG-10827: feat(nbcs): update ose-oauth-proxy image digest reference from 4.8 to the latest 4.14 version (#388)"
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/controllers/notebook_oauth.go
Labels: approved, lgtm

#437 RHOAIENG-15335: feat(odh-nbc/webhook): only update oauth-proxy image in CREATE events
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm

#434 Introduce rbac controller to handle RoleBindings
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_rbac.go
Labels: approved, lgtm, tide/merge-method-squash

#444 Sync v1.9-branch branch with main branch
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_oauth.go
  components/odh-notebook-controller/controllers/notebook_rbac.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm

#432 NO-JIRA: chore(nbcs): update tooling in controller's Makefiles - kubernetes and kustomize
  components/notebook-controller/Makefile
  components/odh-notebook-controller/Makefile
  components/profile-controller/Makefile
Labels: approved, lgtm

#436 RHOAIENG-15335: feat(odh-nbc/webhook): don't initiate updates that would restart a running pod
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/notebook_webhook_utils.go
  components/odh-notebook-controller/controllers/notebook_webhook_utils_test.go
  components/odh-notebook-controller/go.mod
Labels: approved, lgtm

#406 RHOAISTRAT-214: Issue #362: feat(nbcs): build containers to be fips-ready
  components/notebook-controller/Dockerfile
  components/odh-notebook-controller/Dockerfile
Labels: approved, lgtm

#447 RHOAIENG-15741: Sync v1.9-branch branch with main branch
  components/notebook-controller/Makefile
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/notebook_webhook_utils.go
  components/odh-notebook-controller/controllers/notebook_webhook_utils_test.go
  components/odh-notebook-controller/go.mod
  components/profile-controller/Makefile
Labels: approved, lgtm

#448 NO-JIRA: tests(odh-nbc): shorten the test certificates
  components/odh-notebook-controller/controllers/notebook_controller_test.go
Labels: approved, lgtm

#456 RHOAIENG-15875: chore(gha): enable verbose govulncheck output
  .github/workflows/code-quality.yaml
Labels: approved, lgtm, tide/merge-method-squash

#457 RHOAIENG-15875: fix(deps): upgrade protobuf package to unaffected version
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved, lgtm, tide/merge-method-squash

#458 RHOAIENG-15741: Sync v1.9-branch branch with main branch
  .github/workflows/code-quality.yaml
  components/notebook-controller/Dockerfile
  components/notebook-controller/config/overlays/openshift/params.env
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/odh-notebook-controller/Dockerfile
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved

#455 RHOAIENG-15743: fix(odh-nbc): trim ca-bundle certData to avoid logging scary messages
  components/odh-notebook-controller/controllers/notebook_controller.go
Labels: approved, lgtm

#466 Update gha to update makefile-vars.mk external file
  .github/workflows/notebook-controller-images-updater.yaml
Labels: approved, lgtm

#461 RHOAIENG-15772: tests(nbcs): use the direct (uncached) client to drive tests
  components/notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#462 RHOAIENG-15772: tests(odh-nbc): fix unintended shadowing of `cfg` variable
  components/notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#464 RHOAIENG-15772: tests(odh-nbc): disable graceful shutdown period for envtest
  components/odh-notebook-controller/controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#463 RHOAIENG-15772: tests(odh-nbc): wait for controller manager to stop before stopping envtest
  components/odh-notebook-controller/controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#450 RHOAIENG-15772: tests(odh-nbc): write envtest kubeconfig to disk upon request
  components/odh-notebook-controller/README.md
  components/odh-notebook-controller/controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#451 RHOAIENG-15772: tests(odh-nbc): write auditlogs from envtest tests to disk upon request
  components/odh-notebook-controller/README.md
  components/odh-notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/envtest-audit-policy.yaml
Labels: approved, lgtm, tide/merge-method-squash

#454 RHOAIENG-15772: tests(odh-nbc): output struct diffs in gomega failure messages
  components/odh-notebook-controller/controllers/notebook_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash

#433 [Fix] update bash scripts for E2E tests run to propagate failures
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/run-e2e-test-service-mesh.sh
  components/odh-notebook-controller/run-e2e-test.sh
Labels: approved, lgtm, tide/merge-method-squash

#468 RHOAIENG-15748: chore(release): set the main tag to `main`, so we need not update it with digest updater from now on
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, tide/merge-method-squash

#375 RHOAIENG-8390: feat(odh-nbc): search for imagestreams only in the namespace the controller runs in
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_network.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/main.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#473 [RHOAIENG-15141] Fix failing E2E tests
  components/odh-notebook-controller/e2e/helper_test.go
  components/odh-notebook-controller/e2e/notebook_creation_test.go
  components/odh-notebook-controller/e2e/notebook_update_test.go
Labels: approved, lgtm, tide/merge-method-squash

#469 Kubeflow sync release pipeline
  .github/workflows/create-release.yaml
  .github/workflows/kubeflow-release.yaml
  .github/workflows/notebook-controller-images-updater.yaml
  .github/workflows/sync-branches-through-pr.yaml
  .github/workflows/sync-branches.yaml
Labels: approved, lgtm, tide/merge-method-squash

#472 Create a .yaml file with kubeflow version
  components/notebook-controller/config/component_metadata.yaml
  components/notebook-controller/generate-metadata-yaml.sh
Labels: approved, lgtm

#475 Change gitconfig to use --global option
  .github/workflows/notebook-controller-images-updater.yaml
  .github/workflows/sync-branches.yaml
Labels: approved, lgtm

#478 Increase timeouts as they were too short.
  .github/workflows/kubeflow-release.yaml
Labels: approved, lgtm
