Repository opendatahub-io/kubeflow, pull requests merged in 2024-07, with the labels that each got.

#366 chore: add `.snyk` config file to ignore directories that we don't build ODH from
  .snyk
Labels: approved, lgtm, tide/merge-method-squash

#363 Update OWNERS file with adding more approvers
  CONTRIBUTING.md
  OWNERS
Labels: approved, lgtm

#364 Update kustomization to use params env and yml on notebook-controller and odh-notebook-controller
  .github/workflows/odh_notebook_controller_integration_test.yaml
  components/notebook-controller/config/overlays/openshift/kustomization.yaml
  components/notebook-controller/config/overlays/openshift/manager_openshift_patch.yaml
  components/notebook-controller/config/overlays/openshift/params.env
  components/notebook-controller/config/overlays/openshift/params.yaml
  components/odh-notebook-controller/config/base/kustomization.yaml
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/config/manager/kustomization.yaml
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/manager/params.yaml
Labels: approved, lgtm, tide/merge-method-squash

#371 Create gha to update automaticaly the notebook-controller images
  .github/workflows/notebook-controller-images-updater.yaml
Labels: lgtm

#370 [Stable] Update kustomization to use params env and yml on notebook-controller and odh-notebook-controller
  .github/workflows/odh_notebook_controller_integration_test.yaml
  components/notebook-controller/config/overlays/openshift/kustomization.yaml
  components/notebook-controller/config/overlays/openshift/manager_openshift_patch.yaml
  components/notebook-controller/config/overlays/openshift/params.env
  components/notebook-controller/config/overlays/openshift/params.yaml
  components/odh-notebook-controller/config/base/kustomization.yaml
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/config/manager/kustomization.yaml
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/manager/params.yaml
Labels: approved, lgtm

#369 Upgrade the x/net package v0.23.0 for the cve fix
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved, lgtm
