Repository opendatahub-io/kubeflow, pull requests merged in 2025-06, with the labels that each got.

#614 NO-JIRA: chore(gh): permit filling blank github issues on the opendatahub-io/kubeflow repo again
  .github/ISSUE_TEMPLATE/config.yml
Labels: approved, lgtm, size/xs

#610 Add a script to run kustomize on our components to check all works
  ci/kustomize.sh
Labels: approved, lgtm, size/l

#612 NO-JIRA: chore(dev): ensure same webhookCertDir location on Linux and macOS
  components/odh-notebook-controller/main.go
Labels: approved, lgtm, size/xs

#617 Switch SET_PIPELINE_RBAC env to true
  components/odh-notebook-controller/config/manager/manager.yaml
Labels: approved, lgtm, size/xs

#609 RHOAIENG-11681: Running 'kustomize edit fix --vars' on each component to upgrade to kustomize v5
  components/base/kustomization.yaml
  components/notebook-controller/config/crd/kustomization.yaml
  components/notebook-controller/config/default/kustomization.yaml
  components/notebook-controller/config/manager/kustomization.yaml
  components/notebook-controller/config/overlays/kubeflow/kustomization.yaml
  components/notebook-controller/config/overlays/openshift/kustomization.yaml
  components/notebook-controller/config/overlays/openshift/manager_openshift_patch.yaml
  components/notebook-controller/config/overlays/service-mesh/kustomization.yaml
  components/notebook-controller/config/overlays/standalone-service-mesh/kustomization.yaml
  components/notebook-controller/config/overlays/standalone/kustomization.yaml
  components/notebook-controller/config/rbac/kustomization.yaml
  components/odh-notebook-controller/config/base/kustomization.yaml
  components/odh-notebook-controller/config/default/kustomization.yaml
  components/odh-notebook-controller/config/development/kustomization.yaml
  components/odh-notebook-controller/config/manager/kustomization.yaml
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/rbac/kustomization.yaml
  components/odh-notebook-controller/config/webhook/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/l

#620 [GHA-15441731689] Update odh and notebook-controller with image 1.10-452e80c
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#622 Update code-quality.yaml to include kustomize check within code-quality github action
  .github/workflows/code-quality.yaml
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, size/s

#607 RHOAIENG-23204: feat: Introduce dspa secret controller to handle ds-pipeline-config lifecycle
  components/odh-notebook-controller/config/crd/external/opendatahub.io_dashboard.yaml
  components/odh-notebook-controller/config/crd/external/opendatahub.io_dspa.yaml
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_dspa_secret.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
  components/odh-notebook-controller/main.go
Labels: approved, lgtm, tide/merge-method-squash, size/xxl

#627 [RHOAIENG-363] Include service-ca cert bundle to workbench-ca bundle
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
Labels: approved, lgtm, size/m

#623 RHOAIENG-27813: extend coverage for the runtime config map tests
  components/odh-notebook-controller/controllers/notebook_runtime_test.go
Labels: approved, lgtm, size/l

#643 RHOAIENG-25707: test(odh-nbc): additional testcases as per review feedback
  components/odh-notebook-controller/controllers/notebook_webhook_test.go
Labels: tide/merge-method-squash, size/l
