Repository opendatahub-io/kubeflow, pull requests merged in 2025-03, with the labels that each got.

#542 RHOAIENG-12107: chore(components/odh-notebook-controller): replace deprecated `pointer.` usages with `ptr.To` to fix linter checks
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_route.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, size/m

#543 RHOAIENG-12107: chore(components/odh-notebook-controller): delete err parameter from the ensureOAuthNetworkPolicyExists to fix linter check
  components/odh-notebook-controller/e2e/notebook_creation_test.go
Labels: approved, lgtm, ok-to-test, size/xs

#550 Update Konflux references to 493a872 (#377)
  .tekton/kf-notebook-controller-pull-request.yaml
  .tekton/kf-notebook-controller-push.yaml
  .tekton/odh-notebook-controller-pull-request.yaml
  .tekton/odh-notebook-controller-push.yaml
Labels: size/m

#549 [GHA-13765002197] Update odh and notebook-controller with image 1.9-77549e7
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#547 RHOAIENG-18401: chore(konflux): restrict triggering only for the opendatahub-io/kubeflow repository
  .tekton/kf-notebook-controller-pull-request.yaml
  .tekton/kf-notebook-controller-push.yaml
  .tekton/odh-notebook-controller-pull-request.yaml
  .tekton/odh-notebook-controller-push.yaml
Labels: approved, lgtm, size/xs

#551 [GHA-13766514731] Update odh and notebook-controller with image 1.9-74995ca
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#544 RHOAIENG-12107: chore(components/odh-notebook-controller): rewrite Poll function to PollUntilContextTimeout to fix linter error
  components/odh-notebook-controller/e2e/helper_test.go
  components/odh-notebook-controller/e2e/notebook_creation_test.go
  components/odh-notebook-controller/e2e/notebook_deletion_test.go
  components/odh-notebook-controller/e2e/notebook_update_test.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, size/m

#553 RHOAIENG-13916: fix(odh-notebook-controller): handle errored imagestreams in webhook
  components/odh-notebook-controller/config/crd/external/image.openshift.io_imagestream.yaml
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/notebook_webhook_test.go
Labels: approved, tide/merge-method-squash, size/l

#558 [GHA-13841023968] Update odh and notebook-controller with image 1.9-c48320a
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#537 RHOAIENG-5114: feat(build): konflux build on ARM64, Power, Z Architectures
  .tekton/kf-notebook-controller-pull-request.yaml
  .tekton/kf-notebook-controller-push.yaml
  .tekton/odh-notebook-controller-pull-request.yaml
  .tekton/odh-notebook-controller-push.yaml
Labels: approved, lgtm, size/s

#465 RHOAIENG-15772: tests(odh-nbc) significantly reduce the amount of sleeping in tests
  components/odh-notebook-controller/controllers/notebook_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash, size/s

#569 [GHA-13987404080] Update odh and notebook-controller with image 1.9-ca14620
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#571 NO-JIRA: deps({odh-}notebook-controller): update to go1.22
  components/notebook-controller/Dockerfile
  components/notebook-controller/go.mod
  components/odh-notebook-controller/Dockerfile
  components/odh-notebook-controller/go.mod
Labels: approved, lgtm, size/s

#572 NO-JIRA: chore(.tekton/): since ubi8 (and ubi9) minimal images fail in Konflux when subscribed with entitlement certificate, hide the certificate from our build so that it does not fail
  .tekton/kf-notebook-controller-pull-request.yaml
  .tekton/kf-notebook-controller-push.yaml
  .tekton/odh-notebook-controller-pull-request.yaml
  .tekton/odh-notebook-controller-push.yaml
Labels: approved, lgtm, size/s

#570 RHOAIENG-13916: chore(odh-notebook-controller/tests): introduce oTel testing
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/notebook_webhook_test.go
  components/odh-notebook-controller/controllers/opentelemetry_test.go
  components/odh-notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved, size/l
