Repository opendatahub-io/kubeflow, pull requests merged in 2025-01, with the labels that each got.

#493 RHOAIENG-12524: fix(script): Improve generate-metadata-yaml.sh based on feedback
  components/notebook-controller/config/component_metadata.yaml
  components/notebook-controller/generate-metadata-yaml.sh
Labels: approved, lgtm

#504 RHOAIENG-16751: chore(gha): add test for checking the values match between Version file and metadata yaml file
  .github/workflows/code-quality.yaml
  ci/generate_code.sh
Labels: approved, lgtm

#508 chore(deps): bump golang.org/x/net from 0.23.0 to 0.33.0 in /components/{odh-}notebook-controller
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved, lgtm, dependencies, go

#509 [GHA-12791966348] Update odh and notebook-controller with image 1.9-84946ca
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm

#502 RHOAIENG-17634: ref(odh-nbc/tests): create Gomega custom matcher for comparing CRs in kubeflow notebooks tests
  components/odh-notebook-controller/controllers/matchers_test.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
Labels: approved, lgtm

#442 NO-JIRA: tests(odh-nbc): update to the latest route crd
  components/odh-notebook-controller/config/crd/external/route.openshift.io_routes.yaml
Labels: approved, lgtm

#503 RHOAIENG-17634: chore(odh-nbc/tests): implement diff minimization for k8s objects diffs
  components/odh-notebook-controller/controllers/matchers_test.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, size/l
