Repository opendatahub-io/kubeflow, pull requests merged in 2025-04, with the labels that each got.

#585 [GHA-14359206376] Update odh and notebook-controller with image 1.10-47152af
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#586 [GHA-14379433294] Update odh and notebook-controller with image 1.10-2830879
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: size/xs

#588 [GHA-14501400145] Update odh and notebook-controller with image 1.10-8d5f3b5
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#591 NO-JIRA: deps({odh-}notebook-controller): update to go1.23
  components/notebook-controller/Dockerfile
  components/notebook-controller/go.mod
  components/odh-notebook-controller/Dockerfile
  components/odh-notebook-controller/go.mod
Labels: approved, lgtm, size/s

#556 chore(deps): bump golang.org/x/net from 0.33.0 to 0.38.0 in /components/{odh-}notebook-controller
  components/notebook-controller/go.mod
  components/notebook-controller/go.sum
  components/odh-notebook-controller/go.mod
  components/odh-notebook-controller/go.sum
Labels: approved, lgtm, size/m

#574 NO-JIRA: chore(docs): Add guide for upgrading Go version and dependencies
  DEPENDENCIES.md
  README.md
Labels: approved, lgtm, size/m
