Repository opendatahub-io/kubeflow, pull requests merged in 2025-05, with the labels that each got.

#596 NO-JIRA: default to building `--platform=linux/amd64` images in Docker builds
  components/notebook-controller/Makefile
  components/odh-notebook-controller/Makefile
Labels: lgtm, size/xs

#597 [GHA-14883570280] Update odh and notebook-controller with image 1.10-ebb569d
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#603 Read pipeline runtime image name from the imagestream tag
  components/odh-notebook-controller/controllers/notebook_runtime.go
Labels: approved, lgtm, size/s

#593 RHOAIENG-23765: Adjust the image selection to consider notebook namespace
  components/odh-notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_webhook.go
  components/odh-notebook-controller/controllers/notebook_webhook_test.go
  components/odh-notebook-controller/controllers/suite_test.go
  components/odh-notebook-controller/main.go
Labels: approved, lgtm, size/l

#606 RHOAIENG-23765: Add span event when ImageStream isn't found.
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm, size/xs

#539 RHOAI-4148: Re-adjust the statefulset, route, service based on generateName
  components/notebook-controller/controllers/notebook_controller.go
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_oauth.go
  components/odh-notebook-controller/controllers/notebook_route.go
Labels: lgtm, tide/merge-method-squash, size/l

#608 [GHA-15176038300] Update odh and notebook-controller with image 1.10-688c831
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#613 NO-JIRA: chore(dev): log error when imagestream is found but could not be fetched
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm, size/xs
