Repository opendatahub-io/kubeflow, pull requests merged in 2025-07, with the labels that each got.

#645 add @jesuino to OWNERS
  OWNERS
Labels: approved, lgtm, size/xs

#647 Add .editorconfig to enforce coding styles
  .editorconfig
Labels: lgtm, tide/merge-method-squash, size/s

#650 remove ACK_GINKGO_DEPRECATIONS=1.16.5 env var in make test
  components/odh-notebook-controller/Makefile
Labels: approved, lgtm, size/xs

#649 Replace local context.Background() with global context in notebook controller tests
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/controllers/notebook_runtime_test.go
  components/odh-notebook-controller/controllers/notebook_webhook_test.go
  components/odh-notebook-controller/controllers/notebook_webhook_utils_test.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, size/m

#655 [GHA-16343041922] Update odh and notebook-controller with image 1.10-
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/makefile-vars.mk
Labels: approved, lgtm, size/xs

#662 Add logging for INJECT_CLUSTER_PROXY_ENV parse errors
  components/odh-notebook-controller/controllers/notebook_webhook.go
Labels: approved, lgtm, size/xs

#656 Bump go-toolset images from UBI8 to UBI9 and from golang 1.23 to 1.24
  DEPENDENCIES.md
  components/notebook-controller/Dockerfile
  components/notebook-controller/go.mod
  components/odh-notebook-controller/Dockerfile
  components/odh-notebook-controller/controllers/notebook_controller_test.go
  components/odh-notebook-controller/go.mod
Labels: approved, lgtm, size/m

#663 Improve formatKeyName function to handle all invalid ConfigMap key characters
  components/odh-notebook-controller/controllers/notebook_runtime.go
  components/odh-notebook-controller/controllers/notebook_runtime_test.go
Labels: approved, lgtm, tide/merge-method-squash, size/l
